# Generated by Django 4.1.7 on 2023-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_user_date_joined_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
