# Generated by Django 4.1.7 on 2023-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://miramarvet.com.au/wp-content/uploads/2021/08/api-cat2.jpg', max_length=100),
        ),
    ]
